module.exports = {
	name: 'whatsup',
	description: 'Talk with Ciramor. He answers you',
	aliases: ['wu', 'hi'],
	cooldown: 10,
	execute(message) {
		var list = [
            "I'm upset, no one can choose me at Survival.",
            "Just the usual... absorbing evil into my body...",
            "Sealing doors, opening windows...",
            "Spying on pilkim while he spies on girls",
            "Seeing some memories, oooh Catalyna.... sometimes she acts like a stone, other times she explodes like fire....",
            "Sorry, cannot answer now, try discover some secrets from Eredan's Wisdom.",
            "You should try eat the noodles from Ramen's restaurant, it's so delicious and nutritious.",
            "Rumors says that after Alishk enters in the draconic guild looks like all the pigs gone to far from Draconia.",
            "To go and swim with Mylad is dangerous. Bragan could tell you about it",
            "Advice of the Day: Dance being happy, dance like Okooni.",
            //
            "Who are the server whales? I need to ask for a handout.",
            "I'm going to travel to the White Islands, I need to see some things about the Typhon.",
            "Just thinking if I could give my body back to Nehant to demonize certain players.",
            "Rumors says that after Alishk enters in the draconic guild looks like all the pigs gone to far from Draconia.",
            "Did you know that Adrian came from a comet, shaked Guem, and became a Demigod?",
            "Interesting fact: 'S.A.R.A.H.' stands for 'Système Automatisé Réfléchissant à Apparence Humaine'. Something like 'Automated Thinking System with Human Aspect'. Galene told me :face_with_monocle:",
            "Interesting fact: The Zahal's pink rabbit looks innofensive, but have many secrets and powers hidden on it, neither Zahal knows it. How I know? Well, i see behind the spells :face_with_monocle:",
            "Interesting fact: Some of Artrezil's books tell that he brought his shadow to life and called it Zil. But when the Archmage died Zil has lost his real form and was forced to live in the body of  a cat. Some years later the cat's body could not hold the living shadow anymore, so the Triumvirate transfered him into Salem. One day, Zil will shine in his old glory once more, even if that takes searching the one who was believed to be dead. :face_with_monocle:",
            "Interesting fact: Exists a levitating isle with a temple, for so long time it was a pirate territory, but now its the major temple of Antellechia. :face_with_monocle:",
            "Interesting fact: Every year happens a World Cooking Contest, on the Kotoba territory, changing the city all times. Till now, Ramen is undefeated for 4 years using and improving his Kensensei, name of the noodlejutsu. :face_with_monocle:",
            //
            "Interesting fact: From time to time, the World-Tree creates cocoons that appears in the ground, next to it. These cocoons grows, till get a child size. When its hatchs appears one of the new Fruits from the World-Tree, a new Dais. :face_with_monocle:",
            "Interesting fact: Lucyan walked by all the Guem Lands, if you need an explorer, call him, he adapted himself to many situations, he has friends in all places, if you are afraid to do something, call him, not expensive, and I will get 5% of it. :face_with_monocle:",
            "Interesting fact: The kingdom that most people know by the name of Avalonia consists in fact of 7 kingdoms, and Avalonia is only one of them. Together with remaining six, each one has a protector, they are known everywhere:\n-Avalonia : Deirf Geis (formerly) / Johan\n-Baranthe : Kolodan ( more known as Fen'rath )\n-Dhun : Yaril (formerly) / Great Duke\n-Western Highlands : Twins Mergis and Bardiya\n-Lokta'ch : Liezar\n-Valdoria : Kaes\n-Yses : Sevilath",
            "Interesting fact: One of the ruins I visited in the Emerald Desert had engravings saying that there is an entire city made of emerald, beneath Thebirak and Mineptra together.",
            "Interesting fact: What was left of Nehant's prison was only stones. Stones that, due to the intricacies, darkened due to their continuous desecration. Whoever touches one of these stones will have a high risk of being corrupted.",
            "Interesting fact: What I like most about Stonelinkers are the markets, their products leave me dreaming, so many magical items, much better than the draconic stores. Unfortunately I don't have crystals to buy everything, couldn't you help me with that?",
            "Interesting fact: Tempus. A well-hidden secret society. You know almost nothing about them, but you know that they try their best to keep the timeline unchanged, following the book of destiny, created by Eredan.",
            "Interesting fact: The Amethyst Glaciers are still melting, they thought it would stop due to the end of the Sol'ra War, but it continued. But I am sensing an elemental convergence, every day there are currents of wind taking clouds to the north, will this event save the place?",
            "......... WHAT?!",
            "When traveling to the Skylands, I found out that Temujin is terrified of beetles, every time he sees one, he remembers when he was Ateb for a while and starts to falter right afterwards!",
            //
            "I did a research and concluded that 1 out of 2 people is a terrible player, I'm great, so you...",
            "I'm feeling that someone today is going to be lucky in the boosters, and that someone is not you!",
            "*slurp* oops, I ... *slurp* will answer, just let me finish... *sluuuuuuuuuuuuuurp* my noodle.",
            "I heard that Quilingo knows the Wuxi Finger technique, they say he learned from Master Shifu.",
            "Mrs. Koria constantly recounts the great achievements of her trainer, the incredible Master Oogway.",
            "Hey, come here, very close, I cannot talk loud, *if you need 'special' cards, I know a guy who can get you, his name is **Raveneau**.*",
            "Psalm is a great bard, he became very famous after singing 'Toss a coin to the witcher'!",
            "There is a rumor going around that the Syd Ironhand didn't actually lose his arm to a shark but instead lost on a Liar's Dice bet with other pirates.",
            "Sorry, I can't say much today, sometimes ignorance is a blessing.",
            "There are 4 Grand Elementals, if you run into any of them, run away, as they are living calamities!",
            //
            "The Black Tower, they say it is a place with incredible treasures, but almost everyone who ventured to go there, never came back...",
            "The 2nd greatest DJ in the world is a pirate called MC Elektro, the 1st is a Mercenary called Kola.",
            "Take care when entering the forests, the Kuars live in some of them, they can make a miniature of your head of yours and put the voodoo curse on you!",
            "Years ago a Flyn Rider stole the Thunder King's Crown, the crown was recovered, but unfortunately the thief ran away.",
            "Tempus asked Time how much time he has. Time replied to Tempus that Time has as much time as Time has.",
            "When sailing, cover your ears, because mermaids like Leira enchant many sailors singing 'Part of your World' and then drown them in the sea.",
            "Council's Secret: Amnezy still haven't appeared after she escaped from Draconia prison, and now the council is going to hire some investigators to try find any clue about her, she just disappeared like saying *now you see me, now you don't*",
            "Council's Secret: The council gonna get many new members soon, we are needing them because a lot more of work came to us, commissions, officialization, and go on. It's being a little hard to we deal with all those things, even more after we lose some important members.",
            "Council's Secret: Marlok and Abyssien are discussing a lot about an idea, what they didnt notice is that I placed a little invisible stone in every room of the castle, a stone only found in the Edge, I can easily create a link with them using a certain spell, and they will act like a wire. (Their idea seems to be about a crystal [not a draconian, as you probably are going to think, one from the zils] golem made of shadow, but need like rituals to give it life)",
            "Council's Secret: Some weeks ago, the Pirates found a light orb in the ocean, and yesterday they found another, we never seen anything like this, looks like something based in light magic, we are going to call the Witchblades from Draconia to analyze, since they are the best light magic users in whole Guem.",
            //
            "Council's Secret: When Chantelain was revealed as the leader of the Mystic caste, everyone began to distrust others. Every meeting had exchanges of barbs, but apparently the mood is improving.  ",
            "Council's Comment: They are planning to do a new ball, but I'm not really looking forward to participating in it, it is still necessary to show some respect to the other advisors, and also keep an eye on all the manipulation they will perform during this ball, this is the main reason to the ball exists.   ",
            "Council's Comment: I dont know why, but seems like Angelica is stalking me sometimes, she looks so needy, I even try to keep her company, but she starts to gossip a lot about others councillors........",
            "Council's Comment: Please, you need warn me when Marquise is going to do some proposal in the reunions, I'm just getting tired of see he doing all his show to just get attention trying be the star, even seems like he want back to the Zircus.",
            "Council's Comment: Sometimes, when the reunion is so boring, Dandy and his band start helps giving a break singing some songs of the rock album Sitar Hero.",
            "Council's Comment: When entering the Council castle hall, if I smell a scent, I already know that Hasna is somewhere next, and every time she brings a different scent!",
            "I think I saw a Piluminix yesterday, legends are telling that this mystical beast, when tamed, will bring to you the best lucky possible ever, I want so much try find it since he still in this region, but I have a lot of work to do :unamused:",
            "This year is very important in the Edge, its the year when the new group of fog snake eggs will hatch, I have one egg in my home, its already prepared to when hatch, but I still need think on the name to give to the snake... any suggestion?",
            "Today I got the news that half of Eltarite forest is taken by Cypress, so half of the forest is green, the other half is fully rotten, a black forest. The war is not being easy, but I'm gonna help the Sap Hearths, I'm developing a new nature spell, a little hard, but I'm ending it, just wait!",
          ]
          
          message.reply(list[Math.floor(Math.random() * list.length)]);
	},
};